name: .NET CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: UrlShortener

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build